services:
  db:
    image: postgres:15-alpine
    container_name: secrep_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-secrep}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      POSTGRES_DB: ${POSTGRES_DB:-secrep_db}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: secrep_mailhog
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres_data:

